### ISSUE TITLE
Call to a member function get() on null when Geolocate (with caching) is enabled

### ISSUE THREAD

**Issue by glagonikas** [woocommerce/woocommerce-rest-api#147]
**Describe the bug**
When "Geolocate (with page caching support)" is enabled, visiting a URL similar to /whatever/wp-json/wp/v2/posts/None throws a fatal error.

```
[02-Mar-2020 11:57:11 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in /home/site/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php:96
Stack trace:
#0 /home/site/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): WC_Customer_Data_Store_Session->read(Object(WC_Customer))
woocommerce/woocommerce#1 /home/site/public_html/wp-content/plugins/woocommerce/includes/class-wc-customer.php(116): WC_Data_Store->read(Object(WC_Customer))
woocommerce/woocommerce#2 /home/site/public_html/wp-content/plugins/woocommerce/includes/class-wc-cache-helper.php(130): WC_Customer->__construct(0, true)
woocommerce/woocommerce#3 /home/site/public_html/wp-content/plugins/woocommerce/includes/class-wc-cache-helper.php(161): WC_Cache_Helper::geolocation_ajax_get_location_hash()
woocommerce/woocommerce#4 /home/site/public_html/wp-includes/class-wp-hook.php(288): WC_Cache_Helper::geolocation_ajax_redirect('')
woocommerce/woocommerce#5 /home/site/public_html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
woocommerce/woocommerce#6 /home/site/public_ in /home/site/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-customer-data-store-session.php on line 96

```

**To Reproduce**
1. Enable Geolocate (with page caching support) on WooCommerce settings
2. Visit /whatever/wp-json/wp/v2/posts/None

**Expected behavior**
When the "Geolocate" option is enabled, the above returns a 404 page and there is no error.

**Isolating the problem (mark completed items with an [x]):**
- [X] I have deactivated other plugins and confirmed this bug occurs when only WooCommerce plugin is active.
- [X] This bug happens with a default WordPress theme active, or [Storefront](https://woocommerce.com/storefront/).
- [X] I can reproduce this bug consistently using the steps above.

**Comment by glagonikas** [comment]
Hi @tammullen see below. Have you got a staging environment?

```
### WordPress Environment ###

WordPress address (URL): https://xxxxxxx
Site address (URL): https://xxxxxxx
WC Version: 3.9.2
REST API Version: ✔ 1.0.2
Log Directory Writable: ❌ To allow logging
make /home/xxxx/public_html/wp-content/uploads/wc-logs/ writable or define a custom WC_LOG_DIR.

WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: ✔
WP Cron: –
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.15
PHP Post Max Size: 8 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1d

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.44-MariaDB
Max Upload Size: 2 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 3.9.2
WC Database Prefix: wp_
MaxMind GeoIP Database: ✔
Total Database Size: 3427.01MB
Database Data Size: 2976.45MB
Database Index Size: 450.56MB
wp_woocommerce_sessions: Data: 0.08MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.11MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 9.52MB + Index: 12.61MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 6.52MB + Index: 5.03MB + Engine InnoDB
wp_as3cf_items: Data: 1.52MB + Index: 1.31MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.02MB + Index: 0.14MB + Engine InnoDB
wp_feedmanager_channel: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_feedmanager_country: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_feedmanager_feed_status: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_feedmanager_field_categories: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_feedmanager_product_feed: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_feedmanager_product_feedmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_feedmanager_source: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_icl_content_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_core_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_flags: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_languages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_languages_translations: Data: 0.20MB + Index: 0.13MB + Engine InnoDB
wp_icl_locale_map: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_message_status: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_mo_files_domains: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_node: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_reminders: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_strings: Data: 1.52MB + Index: 2.00MB + Engine InnoDB
wp_icl_string_packages: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_icl_string_pages: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_icl_string_positions: Data: 0.16MB + Index: 0.05MB + Engine InnoDB
wp_icl_string_status: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_string_translations: Data: 0.17MB + Index: 0.06MB + Engine InnoDB
wp_icl_string_urls: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translate: Data: 8.52MB + Index: 0.17MB + Engine InnoDB
wp_icl_translate_job: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_icl_translations: Data: 128.67MB + Index: 281.73MB + Engine InnoDB
wp_icl_translation_batches: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_downloads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_icl_translation_status: Data: 2.52MB + Index: 0.06MB + Engine InnoDB
wp_landing_form_data: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 4.47MB + Index: 0.13MB + Engine InnoDB
wp_oses_clicks: Data: 153.70MB + Index: 49.61MB + Engine InnoDB
wp_oses_emails: Data: 1874.00MB + Index: 12.56MB + Engine InnoDB
wp_oses_failures: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_oses_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 34.56MB + Index: 41.69MB + Engine InnoDB
wp_posts: Data: 174.58MB + Index: 23.25MB + Engine InnoDB
wp_termmeta: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wp_terms: Data: 0.30MB + Index: 0.38MB + Engine InnoDB
wp_term_relationships: Data: 2.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.27MB + Index: 0.28MB + Engine InnoDB
wp_usermeta: Data: 0.20MB + Index: 0.17MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wcs_payment_retries: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.28MB + Index: 0.17MB + Engine InnoDB
wp_yoast_seo_meta: Data: 34.56MB + Index: 0.00MB + Engine InnoDB

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (1) ###

WooCommerce: by Automattic – 3.9.2

### Settings ###

API Enabled: –
Force SSL: ✔
Currency: GBP (£)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: composite (composite)
external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
featured (featured-de)
outofstock (outofstock)
outofstock (outofstock-de)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔

### WC Pages ###

Shop base: #5007 - /shop/
Cart: #5 - /cart/
Checkout: #6 - /checkout/
My account: #7 - /my-account/
Terms and conditions: #93 - /terms-conditions/

### Theme ###

Name: Twenty Twenty
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: –

### Action Scheduler ###

Complete: 0
Oldest: –
Newest: –

Pending: 0
Oldest: –
Newest: –

Canceled: 0
Oldest: –
Newest: –

In-progress: 0
Oldest: –
Newest: –

Failed: 0
Oldest: –
Newest: –
```

**Comment by vedanshujain** [comment]
I am not able to reproduce this but based on the stack trace, it looks like frontend libraries are getting loaded in API requests for some reason. Do you have any code snippet or anything else that might cause this?

That said, we can add a protection check to get from session only if its initialized.
