### ISSUE TITLE
Critical Bug class-wc-rest-orders-controller.php:185 since Update

### ISSUE THREAD

**Issue by arturhenryy** [woocommerce/woocommerce-rest-api#63]
**Describe the bug**
Hello since some update my error log is full of this errors

2019-11-04T06:54:11+00:00 CRITICAL Uncaught Error: Call to a member function set_status() on null in /home/wp/disk/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-rest-api/src/Controllers/Version3/class-wc-rest-orders-controller.php:185
Stack trace:
#0 /home/wp/disk/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-rest-api/src/Controllers/Version3/class-wc-rest-crud-controller.php(238): WC_REST_Orders_Controller->save_object(Object(WP_REST_Request), false)
woocommerce/woocommerce#1 /home/wp/disk/wordpress/wp-includes/rest-api/class-wp-rest-server.php(946): WC_REST_CRUD_Controller->update_item(Object(WP_REST_Request))
woocommerce/woocommerce#2 /home/wp/disk/wordpress/wp-includes/rest-api/class-wp-rest-server.php(329): WP_REST_Server->dispatch(Object(WP_REST_Request))
woocommerce/woocommerce#3 /home/wp/disk/wordpress/wp-includes/rest-api.php(309): WP_REST_Server->serve_request('/wc/v3/orders/9...')
woocommerce/woocommerce#4 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(286): rest_api_loaded(Object(WP))
woocommerce/woocommerce#5 /home/wp/disk/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
# in /home/wp/disk/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-rest-api/src/Controllers/Version3/class-wc-rest-orders-controller.php in Zeile 185

**WordPress Environment**
<details>
```

WordPress Umgebung
--
WordPress-Adresse (URL): |   | https://www.breathe-organics.com
Website-Adresse (URL): |   | https://www.breathe-organics.com
WooCommerce-Version: |   | 3.8.0
WooCommerce REST API-Paket: |   | 1.0.2 /home/wp/disk/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-rest-api
Log-Verzeichnis beschreibbar: |   | /home/wp/disk/wordpress/wp-content/uploads/wc-logs/
WordPress-Version: |   | 5.2.4
WordPress Multisite: |   | –
WordPress Speicherlimit: |   | 512 MB
WordPress Debug-Modus: |   |  
WordPress Cron: |   |  
Sprache: |   | de_DE
Externer Objekt-Cache: |   | –


```
</details>

**Comment by juliaamosova** [comment]
Thank you for opening this issue @arturhenryy. 

However, I can't reproduce it. According to the error message you are getting in the logs, the error happens here: 

https://github.com/woocommerce/woocommerce-rest-api/blob/master/src/Controllers/Version3/class-wc-rest-orders-controller.php#L185. 

It looks like you or some other plugin is trying to create or update order via REST API. 

The error says that its calling `set_status()` on `null`, so it means that `$object` in https://github.com/woocommerce/woocommerce-rest-api/blob/master/src/Controllers/Version3/class-wc-rest-orders-controller.php#L185.  is not defined.

The object is fetched from the method `prepare_object_for_database` here:

https://github.com/woocommerce/woocommerce-rest-api/blob/master/src/Controllers/Version3/class-wc-rest-orders-controller.php#L148

Now looking inside `prepare_object_for_database` function:

https://github.com/woocommerce/woocommerce-rest-api/blob/master/src/Controllers/Version3/class-wc-rest-orders-controller.php#L73

The order is constructed here:

https://github.com/woocommerce/woocommerce-rest-api/blob/master/src/Controllers/Version3/class-wc-rest-orders-controller.php#L75

Then returned here:

https://github.com/woocommerce/woocommerce-rest-api/blob/master/src/Controllers/Version3/class-wc-rest-orders-controller.php#L134

Nothing else happens to it in between, just some properties are getting updated in some cases. Either the order is not constructed correctly, or something filters it later. 

Can you try to perform a conflict check by deactivating all the plugins except for WooCommerce and switch the theme to our default [Storefront](https://woocommerce.com/storefront/) theme to see if the issue persists? If no error is shown then it will be great to activate one plugin at a time, place or update order and see if the error appears in order to then figure out what is causing it.

**Comment by juliaamosova** [comment]
@arturhenryy there is another issue open where the author is experiencing the same error as you are:
https://github.com/woocommerce/woocommerce-rest-api/issues/59

By looking at this error, it seems that you are using some kind of a German version of WooCommerce (such as [Germanized for WooCommerce](https://wordpress.org/plugins/woocommerce-germanized/)), is it correct?

> in /home/wp/disk/wordpress/wp-content/plugins/woocommerce/packages/woocommerce-rest-api/src/Controllers/Version3/class-wc-rest-orders-controller.php in Zeile 185

I wonder if the issue has to do with it.

**Comment by juliaamosova** [comment]
@arturhenryy I am closing this issue due to inactivity. Please feel free to comment on it in case we missed something. We'd be happy to take another look.
